#! /bin/sh
#
# line_counter
# Copyright (C) 2016 sabertazimi <sabertazimi@gmail.com>
#
# Distributed under terms of the MIT license.
#

echo "Header Files Line: " && find src/ -name "*.h" | xargs cat | grep -v -e ^$ | wc -l
echo "Source Files Line: " && find src/ -name "*.cpp" | xargs cat | grep -v -e ^$ | wc -l
