webtalk_init -webtalk_dir /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab4/task1/task1.sim/sim_1/synth/func/xsim.dir/_4bit_binary_counter_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun  5 21:29:08 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1538259" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ebf7aa56-942b-4ba1-bd9c-f5a9cfeb0b64" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ef92fe2735e44e1fbeff3de8f2e6950c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2423.828 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "11" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "98 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "11 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "339" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "264" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "47" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.57_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "178312_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3164414667 -regid "" -xml /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab4/task1/task1.sim/sim_1/synth/func/xsim.dir/_4bit_binary_counter_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab4/task1/task1.sim/sim_1/synth/func/xsim.dir/_4bit_binary_counter_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab4/task1/task1.sim/sim_1/synth/func/xsim.dir/_4bit_binary_counter_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
