# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.cache/wt [current_project]
set_property parent.project_path /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/Register_behavior.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/mux_8bit_2to1_behavior.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/Adder_dataflow.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/Data_path_with_mux_adder_register.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/Datapath_with_mux_adder_register_memory.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab4/lab4_1/lab4_1.srcs/sources_1/new/memory.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Datapath_with_mux_adder_register_memory -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Datapath_with_mux_adder_register_memory.dcp

catch { report_utilization -file Datapath_with_mux_adder_register_memory_utilization_synth.rpt -pb Datapath_with_mux_adder_register_memory_utilization_synth.pb }
