# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_3_2/lab2_2_3_2.cache/wt [current_project]
set_property parent.project_path /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_3_2/lab2_2_3_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_2_1/lab2_2_2_1.srcs/sources_1/new/lab2_circuitA_dataflow.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_2_1/lab2_2_2_1.srcs/sources_1/new/comparator_dataflow.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_2_1/lab2_2_2_1.srcs/sources_1/new/lab2_2_2_1_partA.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_1/lab2_1.srcs/sources_1/new/bcd_to_7segment_decoder.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_3_1/lab2_2_3_1.srcs/sources_1/new/fulladder_dataflow.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_2_1/lab2_2_2_1.srcs/sources_1/new/lab2_2_2_1.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_3_1/lab2_2_3_1.srcs/sources_1/new/rca_dataflow.v
  /home/sabertazimi/gitrepo/hust-lab/verilog/lab2/lab2_2_3_2/lab2_2_3_2.srcs/sources_1/new/rca_to_7segment_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top rca_to_7segment_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef rca_to_7segment_dataflow.dcp

catch { report_utilization -file rca_to_7segment_dataflow_utilization_synth.rpt -pb rca_to_7segment_dataflow_utilization_synth.pb }
