DROP SCHEMA IF EXISTS `SPJ414800`;
CREATE SCHEMA `SPJ414800`;
USE `SPJ414800`;

DROP TABLE IF EXISTS `S`;
DROP TABLE IF EXISTS `P`;
DROP TABLE IF EXISTS `J`;
DROP TABLE IF EXISTS `SPJ`;

CREATE TABLE `S` (
	`SNO` VARCHAR(5) PRIMARY KEY,
    `SNAME` VARCHAR(10) NOT NULL,
    `STATUS` INT,
    `CITY` VARCHAR(10)
);

CREATE TABLE `P` (
	`PNO` VARCHAR(5) PRIMARY KEY,
    `PNAME` VARCHAR(10) NOT NULL,
    `COLOR` VARCHAR(5),
    `WEIGHT` INT DEFAULT 10
);

CREATE TABLE `J` (
	`JNO` VARCHAR(5) PRIMARY KEY,
    `JNAME` VARCHAR(10) NOT NULL,
    `CITY` VARCHAR(10)
);

CREATE TABLE `SPJ` (
	`SNO` VARCHAR(5),
    `PNO` VARCHAR(5),
    `JNO` VARCHAR(5),
    `QTY` INT CHECK(`QTY` >= 1 AND `QTY` <= 10000),
    PRIMARY KEY(`SNO`, `PNO`, `JNO`),
    FOREIGN KEY (`SNO`)
		REFERENCES `S`(`SNO`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (`PNO`)
		REFERENCES `P`(`PNO`)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (`JNO`)
		REFERENCES `J`(`JNO`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

