# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.cache/wt [current_project]
set_property parent.project_path /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/rotate_shift_register.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/D_ff.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/signal_source.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/binary_counter.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/timing_signal.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/control_unit.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/clock_generator.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/timingSignalGenerator/timingSignalGenerator.srcs/sources_1/new/timing_signal_generator.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top timing_signal_generator -part xc7a100tcsg324-1


write_checkpoint -force -noxdef timing_signal_generator.dcp

catch { report_utilization -file timing_signal_generator_utilization_synth.rpt -pb timing_signal_generator_utilization_synth.pb }
