# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sabertazimi/Work/Source/dld/clock_report/clock_report.cache/wt [current_project]
set_property parent.project_path /home/sabertazimi/Work/Source/dld/clock_report/clock_report.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sabertazimi/Work/Source/dld/clock_design/src/integer_to_bcd.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/bcd_to_segment.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/time_to_segment.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/flow_led.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/timer.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/time_displayer.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/timing_clock.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/ring.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/tick_divider.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/range_divider.v
  /home/sabertazimi/Work/Source/dld/clock_design/src/clock.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sabertazimi/Work/Source/dld/clock_design/constrs/clock.xdc
set_property used_in_implementation false [get_files /home/sabertazimi/Work/Source/dld/clock_design/constrs/clock.xdc]


synth_design -top clock -part xc7a100tcsg324-1


write_checkpoint -force -noxdef clock.dcp

catch { report_utilization -file clock_utilization_synth.rpt -pb clock_utilization_synth.pb }
