# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.cache/wt [current_project]
set_property parent.project_path /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.srcs/sources_1/new/JK_ff.v
  /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.srcs/sources_1/new/mod10_counter.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.srcs/constrs_1/new/mod10_counter.xdc
set_property used_in_implementation false [get_files /home/sabertazimi/gitrepo/hust-lab/digitalLogic/lab3_2/lab3_2.srcs/constrs_1/new/mod10_counter.xdc]


synth_design -top mod10_counter -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mod10_counter.dcp

catch { report_utilization -file mod10_counter_utilization_synth.rpt -pb mod10_counter_utilization_synth.pb }
