#
# Makefile
# sabertazimi, 2017-03-02 00:42
#

test:
	rm -fr dragoncopy.copy
	rm -fr a.out
	gcc dragoncopy_test.c
	./a.out
	cat dragoncopy.copy

clean:
	rm -fr dragoncopy.copy
	rm -fr a.out

# vim:ft=make
#
