#!/bin/sh

echo Now starting to assemble, compile and link kernel:

# assembling boot code
nasm -f elf -o boot.o boot.asm

# linking *.o files
ld -T link.ld -m elf_i386 -o kernel.bin boot.o

echo Done!
